syntax = "proto3";

package user;

service UserService{
    rpc Register (RegisterRequest) returns (RegisterResponse);
    rpc Auth (AuthRequest) returns (AuthResponse);
    rpc ReAuth (ReAuthRequest) returns (ReAuthResponse);
    rpc GetUser (GetUserRequest) returns (GetUserResponse);
    rpc SetRole (SetRoleRequest) returns (SetRoleResponse);
    rpc GetUsersList (GetUsersListRequest) returns (GetUsersListResponse);
}

message RegisterRequest{
    string login = 1;
    string password = 2;
    string full_name = 3;
}

message RegisterResponse{
    int32 userid = 1;
    string role = 2;
}

message SetRoleRequest{
    int32 userid = 1;
    string role = 2;
}

message SetRoleResponse{
    int32 userid = 1;
    string role = 2;
}

message AuthRequest{
    string login = 1;
    string password = 2;
}

message AuthResponse{
    string access_token = 1;
    string refresh_token = 2;
}

message ReAuthRequest{
    string refresh_token = 1;
}

message ReAuthResponse{
    string access_token = 1;
}

message GetUserRequest{}

message GetUserResponse{
    int32 userid = 1;
    string login = 2;
    string role = 3;
    string full_name = 4;
}

message GetUsersListRequest {}

message GetUsersListResponse{
    repeated GetUserResponse users = 1;
}









