# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0btransaction\"A\n\x12TransactionRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x01\x12\x0e\n\x06source\x18\x03 \x01(\t\"e\n\x13TransactionResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x01\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x0e\n\x06userid\x18\x05 \x01(\x05\"&\n\x15TransactionSetRequest\x12\r\n\x05month\x18\x01 \x01(\t\"\x1a\n\x18\x41llTransactionSetRequest\"P\n\x16TransactionSetResponse\x12\x36\n\x0ctransactions\x18\x01 \x03(\x0b\x32 .transaction.TransactionResponse2\xab\x02\n\x12TransactionService\x12S\n\x0e\x41\x64\x64Transaction\x12\x1f.transaction.TransactionRequest\x1a .transaction.TransactionResponse\x12\\\n\x11GetTransactionSet\x12\".transaction.TransactionSetRequest\x1a#.transaction.TransactionSetResponse\x12\x62\n\x14GetAllTransactionSet\x12%.transaction.AllTransactionSetRequest\x1a#.transaction.TransactionSetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=34
  _globals['_TRANSACTIONREQUEST']._serialized_end=99
  _globals['_TRANSACTIONRESPONSE']._serialized_start=101
  _globals['_TRANSACTIONRESPONSE']._serialized_end=202
  _globals['_TRANSACTIONSETREQUEST']._serialized_start=204
  _globals['_TRANSACTIONSETREQUEST']._serialized_end=242
  _globals['_ALLTRANSACTIONSETREQUEST']._serialized_start=244
  _globals['_ALLTRANSACTIONSETREQUEST']._serialized_end=270
  _globals['_TRANSACTIONSETRESPONSE']._serialized_start=272
  _globals['_TRANSACTIONSETRESPONSE']._serialized_end=352
  _globals['_TRANSACTIONSERVICE']._serialized_start=355
  _globals['_TRANSACTIONSERVICE']._serialized_end=654
# @@protoc_insertion_point(module_scope)
