# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: report.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'report.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creport.proto\x12\x06report\"\x1e\n\rReportRequest\x12\r\n\x05month\x18\x01 \x01(\t\"]\n\x0eReportResponse\x12\x12\n\nprofit_sum\x18\x01 \x01(\x01\x12\x14\n\x0cwithdraw_sum\x18\x02 \x01(\x01\x12\x11\n\ttopup_sum\x18\x03 \x01(\x01\x12\x0e\n\x06userid\x18\x04 \x01(\x05\"2\n\x13\x45xportReportRequest\x12\r\n\x05month\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\",\n\x14\x45xportReportResponse\x12\x14\n\x0c\x64ownload_url\x18\x01 \x01(\t2\xa3\x01\n\rReportService\x12@\n\x0fGetMontlyReport\x12\x15.report.ReportRequest\x1a\x16.report.ReportResponse\x12P\n\x13GetMontlyReportFile\x12\x1b.report.ExportReportRequest\x1a\x1c.report.ExportReportResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTREQUEST']._serialized_start=24
  _globals['_REPORTREQUEST']._serialized_end=54
  _globals['_REPORTRESPONSE']._serialized_start=56
  _globals['_REPORTRESPONSE']._serialized_end=149
  _globals['_EXPORTREPORTREQUEST']._serialized_start=151
  _globals['_EXPORTREPORTREQUEST']._serialized_end=201
  _globals['_EXPORTREPORTRESPONSE']._serialized_start=203
  _globals['_EXPORTREPORTRESPONSE']._serialized_end=247
  _globals['_REPORTSERVICE']._serialized_start=250
  _globals['_REPORTSERVICE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
